name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main  # Trigger this workflow when changes are merged into the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # Specify the runner environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout the code repository

      - name: Install Firebase CLI
        run: npm install -g firebase-tools  # Install Firebase CLI

      - name: Authenticate with Firebase
        run: firebase use --token ${{ secrets.FIREBASE_CI_TOKEN }} --add  # Authenticate with CI token

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0  # Use Firebase Hosting deploy action
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to interact with the repository
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AI_BASED_TRAINING_PLATFO_CA895 }}  # Firebase service account key
          channelId: live  # Deploy to the live channel
          projectId: ai-based-training-platfo-ca895  # Your Firebase project ID


##

##
##y
